// VehicleDataService.h
// Auto-generated by VisCar SDV GenAI Framework
// MISRA-C++:2023 Compliant

#ifndef VEHICLEDATASERVICE_H
#define VEHICLEDATASERVICE_H

#include <memory>
#include <string>
#include <vector>
#include <functional>
#include <stdexcept>

namespace sdv {
namespace services {

// Data Model: VehicleState
struct VehicleState {
    std::string id;
    double timestamp;
    double speed;              // km/h
    double battery_soc;        // State of Charge (0-100%)
    double tyre_pressure_fl;   // Front Left (psi)
    double tyre_pressure_fr;   // Front Right (psi)
    double tyre_pressure_rl;   // Rear Left (psi)
    double tyre_pressure_rr;   // Rear Right (psi)
    int gear;                  // Current gear
    double throttle_position;  // 0-100%
    double brake_position;     // 0-100%
    double steering_angle;     // degrees
    double ev_range;           // km (for EV/Hybrid)
    std::string variant;       // "ICE", "HYBRID", "EV"
    
    VehicleState() : id(""), timestamp(0.0), speed(0.0), battery_soc(0.0),
                     tyre_pressure_fl(32.0), tyre_pressure_fr(32.0),
                     tyre_pressure_rl(32.0), tyre_pressure_rr(32.0),
                     gear(0), throttle_position(0.0), brake_position(0.0),
                     steering_angle(0.0), ev_range(0.0), variant("ICE") {}
};

// Data Model: SensorData
struct SensorData {
    std::string id;
    double timestamp;
    std::string sensor_type;
    double value;
    std::string unit;
    
    SensorData() : id(""), timestamp(0.0), sensor_type(""), value(0.0), unit("") {}
};

// Service: VehicleDataService
class VehicleDataService {
public:
    VehicleDataService();
    ~VehicleDataService();
    
    // Prevent copying (MISRA compliance)
    VehicleDataService(const VehicleDataService&) = delete;
    VehicleDataService& operator=(const VehicleDataService&) = delete;
    
    // Service Interface Methods
    bool getData();
    bool subscribe();
    bool configure();

    // Lifecycle Management
    bool initialize();
    bool shutdown();
    
    // Data Access
    VehicleState getCurrentState() const;
    std::vector<SensorData> getSensorData() const;
    
    // Error Handling
    std::string getLastError() const;
    
private:
    struct Impl;
    std::unique_ptr<Impl> pImpl_;  // PIMPL pattern for ABI stability
    
    bool isInitialized_;
    std::string lastError_;
    VehicleState currentState_;
    
    // Internal helpers
    void logError(const std::string& error);
    bool validateState() const;
    void simulateData();
};

}}  // namespace services / sdv

#endif  // VEHICLEDATASERVICE_H
